@startuml

Abstract Class Dier {
	+ string Naam
	+ int AantalLedematen
	+ Guid Guid
	+ string GetNaam()
	+ string SetNaam()
	+ int GetAantalLedematen()
	+ int SetAantalLedematen()
	+ string toString()
}

Interface IDier {
	+ void PlantVoor();
	+ void Eet();
}

Class Tijger {
}

Class Vogel {
}

Class Vis {
}

Abstract Class Habitat {
	+ List<DierBase> DierenLijst
}

Interface IDierenFactory {
	+ Dier MaakDier();
}

Class Jungle {
}

Class Vogelkooi {
}

Class Aquarium {
}

Class Dierentuin {
	+ Jungle JungleGebied
	+ Vogelkooi VogelkooiGebied
	+ Aquarium AquariumGebied
}

Tijger --|> Dier
Vogel --|> Dier
Vis --|> Dier

Tijger..> IDier
Vogel ..> IDier
Vis ..> IDier

Jungle --|> Habitat
Vogelkooi --|> Habitat
Aquarium --|> Habitat

Habitat ..> IDierenFactory

Jungle o-- Tijger
Vogelkooi o-- Vogel
Aquarium o-- Vis

Dierentuin *-- Jungle
Dierentuin *-- Vogelkooi
Dierentuin *-- Aquarium

@enduml