@startuml

Abstract Class Dier {
	+ string Naam
	+ int AantalLedematen
	+ Guid Guid
	+ string GetNaam()
	+ string SetNaam()
	+ int GetAantalLedematen()
	+ int SetAantalLedematen()
	+ string toString()
}

Interface IPlantVoor {
	+ void PlantVoor()
}

Interface IEet {
	+ void Eet()
}

Class Tijger {
}

Class Vogel {
}

Class Vis {
}

Abstract Class Habitat {
	+ List<DierBase> DierenLijst
}

Class Jungle {
}

Class Vogelkooi {
}

Class Aquarium {
}

Class Dierentuin {
	+ Jungle JungleGebied
	+ Vogelkooi VogelkooiGebied
	+ Aquarium AquariumGebied
}

Tijger --|> Dier
Vogel --|> Dier
Vis --|> Dier

Tijger..> IPlantVoor
Vogel ..> IPlantVoor
Vis ..> IPlantVoor

Tijger ..> IEet
Vogel ..> IEet
Vis ..> IEet

Jungle --|> Habitat
Vogelkooi --|> Habitat
Aquarium --|> Habitat

Jungle o-- Tijger
Vogelkooi o-- Vogel
Aquarium o-- Vis

Dierentuin *-- Jungle
Dierentuin *-- Vogelkooi
Dierentuin *-- Aquarium

@enduml